{
 "title": "Nomad",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Alerts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "ALERTS", "legendFormat": "{{alertname}}" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "nomad_nomad_job_status_running", "legendFormat": "Running Jobs" },
    { "expr": "nomad_nomad_job_status_dead", "legendFormat": "Dead jobs" }
   ]
  },
  {
   "title": "Webserver request handler",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "promhttp_metric_handler_requests_total",
     "legendFormat": "{{job}} | {{code}}"
    }
   ]
  },
  {
   "title": "Nomad jobs",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nomad_nomad_job_summary_running",
     "legendFormat": "{{task_group}}"
    }
   ]
  },
  {
   "title": "Consul services",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "nomad_client_consul_services", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Allocated Cpu",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nomad_client_allocated_cpu", "legendFormat": "{{instance}} " }
   ]
  },
  {
   "title": "Allocated memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "nomad_client_allocated_memory", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}