---
- name: Add RHEL repository
  shell: yum-config-manager --add-repo=https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
  args:
    creates: /etc/yum.repos.d/hashicorp.repo
  become: true

- name: Install Nomad
  package:
    name: nomad
    state: latest
  become: true