---
- name: Add Docker repository
  shell: yum-config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo
  become: true

- name: Install Docker
  package:
    name: docker-ce
    state: latest
  become: true