---
- name: Add Docker repo
  yum_repository:
    name: docker-ce
    description: Docker repo
    baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
    gpgkey: https://download.docker.com/linux/centos/gpg

- name: Install Docker
  package:
    name: docker-ce
    state: latest

- name: Start Docker
  service:
    name: docker
    state: started
    enabled: yes

- name: Add Vagrant user to docker group for managing docker without sudo
  user:
    name: vagrant
    groups: docker
    append: yes