---
- name: Add Docker repo
  yum_repository:
    name: docker-ce
    description: Docker repo
    baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
    gpgkey: https://download.docker.com/linux/centos/gpg

- name: Install Docker
  package:
    name: docker-ce
    state: latest